### ISSUE TITLE
项目编译的 windows版本的时候报错了·····不知道如何解决~

### ISSUE THREAD

**Issue by Popxie** [brickyang/reading-card-generator#5]
= =！

Error: /Users/kaka/Desktop/reading-card-generator/node_modules/app-builder-bin/mac/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/Users/kaka/Desktop/reading-card-generator/node_modules/builder-util/src/util.ts:254:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at unpack (/Users/kaka/Desktop/reading-card-generator/node_modules/app-builder-lib/out/electron/ElectronFramework.js:191:18)
    at Object.prepareApplicationStageDirectory (/Users/kaka/Desktop/reading-card-generator/node_modules/app-builder-lib/src/electron/ElectronFramework.ts:148:50)
    at /Users/kaka/Desktop/reading-card-generator/node_modules/app-builder-lib/src/platformPackager.ts:179:21
    at Generator.next (<anonymous>)
·
·
·
·

**Comment by brickyang** [comment]
这应该是关于 electron-builder 的问题，可以在那边开 issue。

另：我没有在 Windows 平台上测试过，Mac 上可正常打包 Windows app。
